// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkKe2rXCJUbTF2Z24YmdfafzMgnugIik4',
    appId: '1:697028214562:web:d38e681704a3537701ef7b',
    messagingSenderId: '697028214562',
    projectId: 'velotoullouse',
    authDomain: 'velotoullouse.firebaseapp.com',
    databaseURL: 'https://velotoullouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velotoullouse.firebasestorage.app',
    measurementId: 'G-VW4XE7QK6R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwvRA5Q0sH-6eWVq4i6IcoXoa488zBun8',
    appId: '1:697028214562:android:7208e5ef6a3aeb3701ef7b',
    messagingSenderId: '697028214562',
    projectId: 'velotoullouse',
    databaseURL: 'https://velotoullouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velotoullouse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB80SZAeC92XcMSxTc8zwuZFSIrMTEeAwU',
    appId: '1:697028214562:ios:7f59e4cbfe4ba2bf01ef7b',
    messagingSenderId: '697028214562',
    projectId: 'velotoullouse',
    databaseURL: 'https://velotoullouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velotoullouse.firebasestorage.app',
    iosBundleId: 'com.velotoulouse.veloToulouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkKe2rXCJUbTF2Z24YmdfafzMgnugIik4',
    appId: '1:697028214562:web:673f6eac04ef390e01ef7b',
    messagingSenderId: '697028214562',
    projectId: 'velotoullouse',
    authDomain: 'velotoullouse.firebaseapp.com',
    databaseURL: 'https://velotoullouse-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'velotoullouse.firebasestorage.app',
    measurementId: 'G-6EQHK99JV3',
  );
}
